require: rubocop-performance

AllCops:
  Exclude:
  - 'bin/*'
  - 'node_modules/**/*'
  - 'db/schema.rb'
  - 'app/models/achievements/**/*'

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
  - 'db/migrate/*'

Rails:
  Enabled: true
Rails/InverseOf:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'app/controllers/*'
Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: slashes
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact
